"""
Copyright (c) 2025 Ynosound.
All rights reserved.

See LICENSE file in the project root for full license information.
"""
import random

from muses.base.temporals import Piece

from ctor.continuator import Continuator2

from midi_stuff.mini_muse import Note


def note_from_temporal_note(n):
    return Note(n.pitch, n.velocity, n.duration(), n.start_time)


def get_best_viewpoint_for(generator, note):
    candidates = [vp for vp in generator.vom.all_unique_viewpoints if
                  (vp != generator.get_start_vp() and vp != generator.get_end_vp() and vp[0] == note.pitch)]
    if candidates:
        return random.choice(candidates)

    # takes the vp with closest pitch
    candidates2=[vp for vp in generator.vom.all_unique_viewpoints if
                  (vp != generator.get_start_vp() and vp != generator.get_end_vp())]
    best=129
    cand3 =[]
    for vp in candidates2:
        d = abs(vp[0] - note.pitch)
        if d == best:
            cand3.append(vp)
        else:
            if d < best:
                best = d
                cand3 = [vp]
    return random.choice(cand3)

if __name__ == '__main__':
    # Initialize the model
    midi_file_path = "../data/prelude_c.mid"
    generator = Continuator2(midi_file_path, 3, transposition=False)

    # get midi file generated by transformer
    piece = Piece.load_midi("../data/prelude_nano_gpt.mid")
    # transform TemporalNote into Note fuck
    temp_note_list = piece.melodies[0].temporals

    note_list = [note_from_temporal_note(n) for n in temp_note_list]

    generated_sequence = [get_best_viewpoint_for(generator, note) for note in note_list]

    # generate the viewpoint sequence:
    # generated_sequence = generator.sample_sequence(length=100, constraints=constraints)

    # remove start or end viewpoint if needed
    # sequence_to_render = generated_sequence
    # sequence_to_render = generated_sequence[0:-1]
    sequence_to_render = generated_sequence[0:-1]

    # realize the sequence (with actual notes)
    rendered_sequence = generator.realize_vp_sequence(sequence_to_render)

    # save the generated sequence
    generator.save_midi(rendered_sequence, "../data/prelude_nanogpt_realized.mid", tempo=-1)
